#!/bin/sh
# Autogenerated udev bootstrap for Silicon Motion USB Display

start_service() { systemctl start smiusbdisplay; }
stop_service()  { systemctl stop  smiusbdisplay; }

create_siliconmotion_symlink() {
  root=$1; device_id=$2; devnode=$3
  mkdir -p "$root/siliconmotion/by-id"
  ln -sf "$devnode" "$root/siliconmotion/by-id/$device_id"
}

unlink_siliconmotion_symlink() {
  root=$1; devname=$2
  for f in "$root/siliconmotion/by-id/"*; do
    { [ ! -e "$f" ] || { [ -L "$f" ] && [ "$f" -ef "$devname" ]; }; } && unlink "$f" 2>/dev/null || true
  done
  (cd "$root" && rmdir -p --ignore-fail-on-non-empty siliconmotion/by-id 2>/dev/null) || true
}

main() {
  action=$1; root=$2; devnode=$4
  case "$action" in
    add)
      device_id=$3
      create_siliconmotion_symlink "$root" "$device_id" "$devnode"
      start_service
      ;;
    remove)
      devname=$3
      unlink_siliconmotion_symlink "$root" "$devname"
      ;;
    START)
      start_service
      ;;
  esac
}

main "$@"
